stream_location: https://example.com/dash/stream

video_source:
    - videotestsrc:
        pattern: 1
    - capsfilter:
        caps: video/x-raw, width = 1920, height = 1080, framerate = 30/1

audio_source:
    - audiotestsrc

video_rates:
    - _low:
        width: 640
        height: 360
        bitrate: 500
    - _med:
        width: 1280
        height: 720
        bitrate: 1500
    - _high:
        width: 1920
        height: 1080
        bitrate: 5000

audio_settings:
    bitrate: 128

schedule:
    - daily:
        "16:30": start
        "18:00": stop
    - monday:
        "03:15": start
        "05:00": stop
    - sunday:
        "08:15": start
        "12:45": stop
